export const config = {
	runtime: "nodejs",
};

export async function GET(request) {
	const url = new URL(
		request.url,
		`https://${request.headers.host || "resolver.vercel.app"}`,
	);
	const urlData = url.searchParams.get("url");

	if (!urlData) {
		return Response.json({
			message: "URL not found.",
			status: 404,
		});
	}

	// Read before Adding Domain //
	// ========================= //
	// pastikan domain memiliki extension (.com .net dsb)
	// pastikan format script sebelum push (biome)
	// pastikan sort domain sebelum push (sort line ascending)
	// ========================= //
	// Read before Adding Domain //

	const rules = [
		// Active Services
		{ domains: ["1fichier.com"], handler: "fichier" },
		{ domains: ["0807.st"], handler: "zeroeightseven" },
		{ domains: ["123av.com"], handler: "javplayer" },
		{ domains: ["javsin.net"], handler: "javsin" },
		{ domains: ["akirabox.com", "akirabox.to"], handler: "akirabox" },
		{ domains: ["akmfiles.com", "akmfls.xyz"], handler: "akmfiles" },
		{ domains: ["androiddatahost.com"], handler: "androiddatahost" },
		{ domains: ["androidfilehost.com"], handler: "androidfilehost" },
		{ domains: ["apkadmin.com", "sharemods.com"], handler: "apkadmin" },
		{ domains: ["aceimg.com"], handler: "aceimg" },
		{ domains: ["berkasdrive.com"], handler: "berkasdrive" },
		{
			domains: ["buzzheavier.com", "bzzhr.co", "bzzhr.to"],
			handler: "buzzheavier",
		},
		{ domains: ["cdeyy.de"], handler: "cdeyy" },
		{ domains: ["datanodes.to"], handler: "datanodes" },
		{
			domains: [
				// "1fichier.com", // Handled by MLTB
				"4shared.com",
				"4tube.com",
				"academicearth.org",
				"acast.com",
				"add-anime.net",
				"ahctv.com",
				"air.mozilla.org",
				"alfafile.net",
				"allocine.fr",
				"alphaporno.com",
				"alterupload.com",
				"animalist.com",
				"animalplanet.com",
				"anysex.com",
				"aparat.com",
				"apkadmin.com",
				"audi-mediacenter.com",
				"audioboom.com",
				"audiomack.com",
				"beeg.com",
				"camdemy.com",
				"chilloutzone.net",
				"cinema.arte.tv",
				"cjoint.net",
				"clickndownload.click",
				"clickndownload.link",
				"clickndownload.org",
				"clickndownload.space",
				"clicknupload.cc",
				"clicknupload.club",
				"clicknupload.co",
				"clicknupload.download",
				"clicknupload.link",
				"clicknupload.org",
				"clicknupload.space",
				"clicknupload.vip",
				"clipwatching.com",
				"clubic.com",
				"clyp.it",
				"concert.arte.tv",
				"creative.arte.tv",
				"daclips.in",
				"dailymail.co.uk",
				"dailymotion.com",
				"darkibox.com",
				"ddc.arte.tv",
				"ddl.to",
				"ddownload.com",
				"democracynow.org",
				"desfichiers.com",
				"destinationamerica.com",
				"dfichiers.com",
				"discovery.com",
				"discoverylife.com",
				"dl4free.com",
				"dotsub.com",
				"drop.download",
				"dropapk.to",
				// "dropbox.com", // Handled by MLTB
				"dropgalaxy.in",
				"e.pcloud.link",
				"ebaumsworld.com",
				"eitb.tv",
				"elfile.net",
				"elitefile.net",
				"ellentube.com",
				"ellentv.com",
				"embed.redtube.com",
				"emload.com",
				"fastbit.cc",
				"fikper.com",
				"file-upload.com",
				"file.al",
				"fileaxa.com",
				"filecat.net",
				"filedot.to",
				"filedot.xyz",
				"filenext.com",
				"filer.net",
				"filesfly.cc",
				"filespace.com",
				"filestore.me",
				"flashbit.cc",
				"flipagram.com",
				"footyroom.com",
				"formula1.com",
				"franceculture.fr",
				"future.arte.tv",
				"gameinformer.com",
				"gamersyde.com",
				"gigapeta.com",
				// "gofile.io", // Handled by MLTB
				"goloady.com",
				"gorillavid.in",
				"gulf-up.com",
				"harefile.com",
				"hbo.com",
				"hellporno.com",
				"hentai.animestigma.com",
				"hexupload.net",
				"hitf.cc",
				"hitf.to",
				"hitfile.net",
				"hornbunny.com",
				"htfl.net",
				"html5-player.libsyn.com",
				"hulkshare.com",
				"imdb.com",
				"info.arte.tv",
				"instagram.com",
				"investigationdiscovery.com",
				"isra.cloud",
				"itar-tass.com",
				"jamendo.com",
				"jove.com",
				"jumploads.com",
				"k.to",
				"katfile.com",
				"keek.com",
				"keezmovies.com",
				"khanacademy.org",
				"kickstarter.com",
				"krasview.ru",
				"kshared.com",
				"la7.it",
				"lci.fr",
				"libsyn.com",
				"liveleak.com",
				"livestream.com",
				"load.to",
				"m.mgoon.com",
				"md3b0j6hj.com",
				"mdy48tn97.com",
				"mediafile.cc",
				// "mediafire.com", // Handled by MLTB
				// "mega.co.nz", // Handled by MLTB
				// "mega.nz", // Handled by MLTB
				"megadl.fr",
				"megadl.org",
				"mesfichiers.fr",
				"mesfichiers.org",
				"metacritic.com",
				"mexa.sh",
				"mexashare.com",
				"mgoon.com",
				"mixcloud.com",
				"mixdrop.ag",
				"mixdrop.club",
				"mixdrop.co",
				"mixdrop.si",
				"mixdrop.sx",
				"mixdrop.to",
				"mixdrop.vc",
				"modsbase.com",
				"mojvideo.com",
				"movieclips.com",
				"movpod.in",
				"mp4upload.com",
				"musicplayon.com",
				"mx-sh.net",
				"myspass.de",
				"myvidster.com",
				"nelion.me",
				"new.livestream.com",
				"news.yahoo.com",
				"odatv.com",
				"onionstudios.com",
				"opvid.online",
				"opvid.org",
				"ora.tv",
				"piecejointe.net",
				// "pixeldrain.com", // Handled by MLTB
				"pjointe.com",
				"play.fm",
				"play.lcp.fr",
				"player.vimeo.com",
				"player.vimeopro.com",
				"plays.tv",
				"playvid.com",
				"playvidto.com",
				"pornhd.com",
				"pornhub.com",
				"prefiles.com",
				"pyvideo.org",
				"rapidfileshare.net",
				"rapidgator.asia",
				// "rapidgator.net", // Handled by MLTB
				"redtube.com",
				"reverbnation.com",
				"revision3.com",
				"rg.to",
				"rts.ch",
				"rtve.es",
				"salefiles.com",
				"sbs.com.au",
				"sciencechannel.com",
				"screen.yahoo.com",
				"screencast.com",
				"scribd.com",
				"seeker.com",
				"sendit.cloud",
				"sendspace.com",
				"sharemods.com",
				"simfileshare.net",
				"sites.arte.tv",
				"skysports.com",
				"slutload.com",
				"soundcloud.com",
				"soundgasm.net",
				"sports.yahoo.com",
				"steamcommunity.com",
				"steampowered.com",
				"store.steampowered.com",
				"stream.cz",
				"streamable.com",
				"streamcloud.eu",
				"streamtape.com",
				"streamtape.net",
				"subyshare.com",
				"sunporno.com",
				"supervideo.tv",
				"tass.ru",
				"teachertube.com",
				"teamcoco.com",
				"ted.com",
				"tenvoi.com",
				// "terabox.app", // Handled by MLTB
				// "terabox.com", // Handled by MLTB
				"terabytez.org",
				"tezfiles.com",
				"tfo.org",
				"thescene.com",
				"thesixtyone.com",
				"tlc.com",
				"tnaflix.com",
				"touch.dailymotion.com",
				"trbbt.net",
				"trubobit.com",
				"trutv.com",
				"tu.tv",
				"turb.cc",
				"turb.pw",
				"turb.to",
				"turbabit.com",
				"turbo.cc",
				"turbo.fr",
				"turbo.to",
				"turbobif.com",
				"turbobit.cc",
				"turbobit.cloud",
				"turbobit.live",
				"turbobit.net",
				"turbobit.online",
				"turbobit.pw",
				"turbobit.ru",
				"turboblt.co",
				"turboget.net",
				"tweakers.net",
				"u.pcloud.link",
				"unsafespeech.com",
				"up-4ever.net",
				"up-load.io",
				"upload-4ever.com",
				"upload42.com",
				"uploadboy.com",
				"uploadev.com",
				"uploadev.org",
				"uploadrar.com",
				"uploadydl.com",
				"uppit.com",
				"upvid.biz",
				"upvid.cloud",
				"upvid.co",
				"upvid.host",
				"upvid.live",
				"upvid.pro",
				"uqload.co",
				"uqload.com",
				"uqload.io",
				"uqload.to",
				"userscloud.com",
				"usersdrive.com",
				"userupload.net",
				"ustream.tv",
				"vbox7.com",
				"veehd.com",
				"velocity.com",
				"veoh.com",
				"vev.io",
				"vid.me",
				"video.arte.tv",
				"video.foxbusiness.com",
				"video.foxnews.com",
				"video.insider.foxnews.com",
				"video.yahoo.com",
				"videodetective.com",
				"videos.sapo.ao",
				"videos.sapo.cv",
				"videos.sapo.mz",
				"videos.sapo.pt",
				"videos.sapo.tl",
				"videzz.net",
				"vidoza.net",
				"vidoza.org",
				"vidto-do.com",
				"vidtodo.com",
				"vimeo.com",
				"vimeopro.com",
				"vipfile.cc",
				"wat.tv",
				"wayupload.com",
				"wdupload.com",
				"wimp.com",
				"world-files.com",
				"worldbytez.com",
				"wupfile.com",
				"www.arte.tv",
				"www.dailymail.co.uk",
				"www.pornhub.com",
				"www.redtube.com",
				"www.sbs.com.au",
				"xtube.com",
				"yahoo.com",
				"yodbox.com",
				"youdbox.com",
				"youporn.com",
			],
			handler: "debrid",
		},
		{ domains: ["devuploads.com"], handler: "devuploads" },
		{
			domains: [
				"d-s.io",
				"d0000d.com",
				"d000d.com",
				"d0o0d.com",
				"do0od.com",
				"do7go.com",
				"dood.cx",
				"dood.la",
				"dood.li",
				"dood.pm",
				"dood.re",
				"dood.sh",
				"dood.so",
				"dood.stream",
				"dood.to",
				"dood.video",
				"dood.watch",
				"dood.wf",
				"dood.work",
				"dood.ws",
				"dood.yt",
				"doods.pro",
				"doods.yt",
				"doodstream.co",
				"doodstream.com",
				"dooodster.com",
				"dooood.com",
				"doply.net",
				"ds2play.com",
				"ds2video.com",
				"dsvplay.com",
				"myvidplay.com",
				"playmogo.com",
				"vide0.net",
				"videyz.lol",
				"vidply.com",
			],
			handler: "dood",
		},
		{ domains: ["dropbox.com"], handler: "dropbox" },
		{ domains: ["easyupload.io"], handler: "easyupload" },
		{ domains: ["fileditch.com", "fileditchfiles.me"], handler: "fileditch" },
		{
			domains: [
				"cabecabean.lol",
				"embedwish.com",
				"filelions.live",
				"filelions.online",
				"filelions.site",
				"filelions.to",
				"kissmovies.net",
				"kitabmarkaz.xyz",
				"mycloudz.cc",
				"streamwish.com",
				"streamwish.to",
				"swdyu.com",
				"vidhide.com",
				"vidhidepro.com",
				"wishfast.top",
			],
			handler: "filelions_and_streamwish",
		},
		{ domains: ["filemirage.com"], handler: "filemirage" },
		{ domains: ["filepress.cloud", "filepress.today"], handler: "filepress" },
		{ domains: ["filester.me"], handler: "filester" },
		{ domains: ["fuckingfast.co"], handler: "fuckingfast" },
		{
			domains: ["gdflix.dev", "gdflix.net"],
			handler: "gdflix",
		},
		{ domains: ["gigafile.nu"], handler: "gigafile" },
		{ domains: ["github.com"], handler: "github" },
		{ domains: ["gofile.io"], handler: "gofile" },
		{ domains: ["hexupload.net"], handler: "hexupload" },
		{ domains: ["hxfile.co"], handler: "hxfile" },
		{
			domains: [
				"cdn.ctrlfilms.eu.org",
				"cloud-oyen.eu.org",
				"database.s3cr3t.workers.dev",
				"index.3nk.workers.dev",
				"seikel.web.id",
				"share.eqrtz.workers.dev",
				"sineflix.ultradrivecloud.workers.dev",
				"somestuff.web.id",
			],
			handler: "index",
		},
		{ domains: ["javplayer.cc"], handler: "javplayer" },
		{ domains: ["krakenfiles.com"], handler: "krakenfiles" },
		{
			domains: ["cdn.0000456.xyz", "dl.0000456.xyz", "index.0000456.xyz"],
			handler: "kurumi",
		},
		{
			domains: [
				"lbx.to",
				"linkbox.cloud",
				"linkbox.to",
				"linkbox.zone",
				"telbx.net",
				"teltobx.net",
			],
			handler: "linkbox",
		},
		{
			domains: [
				"cdn.vidjxeq.com",
				"doey07s.com",
				"dood-hd.com",
				"doodbd.com",
				"doodlix.com",
				"doodlix.org",
				"doodmr.net",
				"doodmv.com",
				"doodmv.net",
				"doodtv.net",
				"jumplixytd.com",
				"lixstream.com",
				"openvideoink.com",
				"poopmv.com",
				"poopmv.net",
				"poopmv.org",
				"poopxy.com",
				"streamlinkccy.com",
				"teraboxtv.net",
				"teramv.com",
				"teratvs.org",
				"teratws.org",
				"twimg.shop",
				"vdayb.pro",
				"vidc08.com",
				"vidcloudmv.org",
				"vidcloudtv.net",
				"vidco0.com",
				"vide-q.com",
				"vide0.me",
				"vide8.me",
				"video-twimg.mx",
				"video-twimg.vip",
				"videqq.net",
				"videqstoresoy.com",
				"videy.red",
				"videy.tv",
				"videyf.com",
				"videymf.com",
				"videymv.com",
				"videymv.net",
			],
			handler: "lixstream",
		},
		{ domains: ["lulacloud.com"], handler: "lulacloud" },
		{ domains: ["mediafile.cc"], handler: "mediafile" },
		{ domains: ["mediafire.com"], handler: "mediafire" },
		{ domains: ["mp4upload.com"], handler: "mp4upload" },
		{ domains: ["odrive.com"], handler: "odrive" },
		{ domains: ["1drv.ms"], handler: "onedrive" },
		{ domains: ["osdn.net"], handler: "osdn" },
		{ domains: ["pandafiles.com"], handler: "pandafiles" },
		{
			domains: [
				"pixeldrain.com",
				"pixeldrain.dev",
				"pixeldra.in",
				"pixeldrain.net",
			],
			handler: "pixeldrain",
		},
		{
			domains: [
				"dood.lu",
				"dood.meme",
				"mp4cash.com",
				"poop.direct",
				"poop.vin",
				"poophd.com",
				"poopstream.com",
				"videyf.pro",
			],
			handler: "poop",
		},
		{ domains: ["qiwi.gg"], handler: "qiwi" },
		{ domains: ["racaty.com", "racaty.io", "racaty.net"], handler: "racaty" },
		{ domains: ["rapidgator.net"], handler: "rapidgator" },
		{ domains: ["rootz.so"], handler: "rootz" },
		{ domains: ["romsget.io"], handler: "romsget" },
		{ domains: ["send.cm"], handler: "send" },
		{ domains: ["sharer"], handler: "sharer" },
		{ domains: ["sfile.mobi"], handler: "sfile" },
		{ domains: ["shrdsk.me"], handler: "shrdsk" },
		{
			domains: [
				"adhoy.de",
				"siicedriva.com",
				"slicedrive.com",
				"slicidrive.com",
				"slicsdrive.com",
				"slizedrive.com",
				"twing.live",
			],
			handler: "slicedrive",
		},
		{ domains: ["solidfiles.com"], handler: "solidfiles" },
		{
			domains: ["sourceforge.com", "sourceforge.net"],
			handler: "sourceforge",
		},
		{ domains: ["streamhub.ink", "streamhub.to"], handler: "streamhub" },
		{
			domains: [
				"advtpe.com",
				"streamta.pe",
				"streamtape.cc",
				"streamtape.co",
				"streamtape.com",
				"streamtape.net",
				"streamtape.to",
				"streamtape.xyz",
			],
			handler: "streamtape",
		},
		{ domains: ["streamvid.net"], handler: "streamvid" },
		{ domains: ["swisstransfer.com"], handler: "swisstransfer" },
		{
			domains: [
				"1024tera.com",
				"1024terabox.com",
				"4funbox.com",
				"freeterabox.com",
				"gibibox.com",
				"goaibox.com",
				"mirrobox.com",
				"momerybox.com",
				"nephobox.com",
				"terabox.app",
				"terabox.club",
				"terabox.com",
				"teraboxapp.com",
				"teraboxlink.com",
				"teraboxshare.com",
				"terafileshare.com",
				"terasharelink.com",
			],
			handler: "terabox",
		},
		{ domains: ["tmpsend.com"], handler: "tmpsend" },
		{ domains: ["transfer.it"], handler: "transfer" },
		{ domains: ["tusfiles.com", "tusfiles.net"], handler: "tusfiles" },
		{ domains: ["uc-share.com"], handler: "ucweb" },
		{ domains: ["u.pcloud.link"], handler: "pcloud" },
		{ domains: ["upload.ee"], handler: "uploadee" },
		{ domains: ["uploadhaven.com"], handler: "uploadhaven" },
		{ domains: ["uploadrar.com"], handler: "uploadrar" },
		{ domains: ["videza.co"], handler: "videza" },
		{ domains: ["vidmonstr.com"], handler: "videq" },
		{ domains: ["vidwara.online"], handler: "vidwara" },
		{
			domains: [
				"vidara.to",
				"vidara.so",
				"vidara.cc",
				"vidvara.cc",
				"weekendletters.shop",
				"weekendletters.cc",
				"uidara.pro",
			],
			handler: "vidara",
		},
		{
			domains: [
				"cdeyy.de",
				"doodd.stream",
				"twing.ink",
				"videy.co",
				"vifey.de",
				"wiidoy.com",
			],
			handler: "videy",
		},
		{ domains: ["videe.cc"], handler: "videe" },
		{
			domains: [
				"bejos.cloud",
				"doey07s.com",
				"dood.ac",
				"dood.am",
				"dood.fans",
				"dood.is",
				"dood.lu",
				"dood.meme",
				"dood.page",
				"dood.tips",
				"doodf.com",
				"doodmv.com",
				"doods.am",
				"doods.at",
				"hek.al",
				"imgd.cx",
				"lixvy.de",
				"mp4.bio",
				"mp4cash.com",
				"p8p.pro",
				"p8p.tube",
				"plaver.de",
				"pooo.st",
				"poop.asia",
				"poop.blue",
				"poop.direct",
				"poop.ee",
				"poop.li",
				"poop.name",
				"poop.onl",
				"poop.top",
				"poop.vin",
				"poop18.com",
				"poophd.com",
				"poophd.me",
				"poophd.net",
				"poophd.pm",
				"poophd.pro",
				"poopki.com",
				"poops.id",
				"poops.video",
				"poopstream.cloud",
				"poopstream.net",
				"poopx.pro",
				"streamable.cloud",
				"streamrizz.com",
				"twlnmg.com",
				"uideo.my",
				"upl.ad",
				"vco.li",
				"vdaq.de",
				"vdiz.de",
				"vdko.de",
				"vid.skin",
				"vid7.online",
				"vid9.live",
				"vidbe.st",
				// "vide.", // Invalid domain
				"vide.cx",
				"vide.ws",
				"vide10.com",
				"vide14.com",
				"vide20.com",
				// "videeq.", // Invalid domain
				"videeq.com",
				"cdn.up2file.online",
				"video.twimg.skin",
				"videq-r.com",
				// "videq.", // Invalid domain
				"videq.cloud",
				"videq.pro",
				"videq.stream",
				"videw.online",
				"videy.to",
				"vidgy.de",
				// "vidoy.", // Invalid domain
				"up2file.online",
				"vidstrm.mom",
				"vydeq.fun",
			],
			handler: "videq",
		},
		{
			domains: ["vik1ngfile.site", "vikingf1le.us.to", "vikingfile.com"],
			handler: "vikingfile",
		},
		{ domains: ["viode.de"], handler: "viode" },
		{
			domains: [
				"justpaste.it",
				"justpaste.me",
				"justpaste.pro",
				"weekendletters.store",
			],
			handler: "justpaste",
		},
		{
			domains: ["aveimg.com", "vivoy.co"],
			handler: "vivoy",
		},
		{ domains: ["we.tl", "wetransfer.com"], handler: "wetransfer" },
		{ domains: ["disk.yandex", "yadi.sk"], handler: "yandex" },
		// Dead Services
		{
			domains: [
				"anonfiles.com",
				"bayfiles.com",
				"filechan.org",
				"hotfile.io",
				"letsupload.cc",
				"letsupload.io",
				"lolabits.se",
				"megaupload.nz",
				"myfile.is",
				"openload.cc",
				"rapidshare.nu",
				"share-online.is",
				"uptobox.com",
				"uptobox.fr",
				"upvid.cc",
				"vshare.is",
				"zippyshare.com",
			],
			handler: "dead",
		},
	];

	const match = rules.find((rule) =>
		rule.domains.some((d) => urlData.includes(d)),
	);

	if (match) {
		const domain = match.domains.find((d) => urlData.includes(d));

		return Response.json({
			message: {
				domain: domain,
				handler: match.handler,
				url: urlData,
			},
			status: 200,
		});
	}

	return Response.json({
		message: "URL not supported.",
		status: 404,
	});
}
